import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Portugal World Cup 2026 Home Jersey',
    price: 1100,
    category: 'Football',
    description: 'Portugal New Jersey for the 2026 World Cup. Authentic Thai Premium quality with moisture-wicking technology.',
    image: 'https://i.ibb.co.com/rGLkYbBM/1.webp',
    colors: ['#E4251B', '#00662E'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true
  },
  {
    id: '2',
    name: 'Germany World Cup 2026 Home Jersey',
    price: 1100,
    category: 'Football',
    description: 'Germany World Cup 2026 Jersey. Sleek design featuring the iconic DFB aesthetic.',
    image: 'https://i.ibb.co.com/KjBphY94/2.webp',
    colors: ['#FFFFFF', '#000000'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true
  },
  {
    id: '3',
    name: 'Argentina World Cup 2026 Home Jersey',
    price: 1100,
    category: 'Football',
    description: 'Argentina New Jersey 2026. Albiceleste pride with the legendary three stars.',
    image: 'https://i.ibb.co.com/d4DhfF3D/3.webp',
    colors: ['#75AADB', '#FFFFFF'],
    sizes: ['S', 'M', 'L', 'XL'],
    isPopular: true
  },
  {
    id: '4',
    name: 'Barcelona Away Black Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Barcelona Black Mamba Jersey 2025. A bold, stealthy look for the Catalan giants.',
    image: 'https://i.ibb.co.com/6hdXLZn/4.webp',
    colors: ['#000000', '#DB0030'],
    sizes: ['S', 'M', 'L', 'XL'],
    isPopular: true
  },
  {
    id: '5',
    name: 'Man City 3rd Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Manchester City 25/26 Third Kit. Best price in Bangladesh for authentic premium gear.',
    image: 'https://i.ibb.co.com/WWpfgSvR/5.webp',
    colors: ['#000000', '#00FF00'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '6',
    name: 'Manchester United Third Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Man United Black Jersey 2025. Classic red devil detailing on a premium black base.',
    image: 'https://i.ibb.co.com/fGxN3nYR/6.webp',
    colors: ['#000000', '#DA291C'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '7',
    name: 'Liverpool Away Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Liverpool Off-White Jersey 2025. Elegant design for the Reds on the road.',
    image: 'https://i.ibb.co.com/tPk5Vr8d/7.jpg',
    colors: ['#F5F5F5', '#00B2A9'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '8',
    name: 'Barcelona Third Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Barcelona Orange Jersey 2025. Vibrant third kit celebrating club heritage.',
    image: 'https://i.ibb.co.com/DHnDMqKs/8.jpg',
    colors: ['#FF8C00', '#004D98'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '9',
    name: 'Al Nassr Third Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Al Nassr White Jersey 2025. Clean white design featuring the club crest.',
    image: 'https://i.ibb.co.com/nqNfC98j/9.webp',
    colors: ['#FFFFFF', '#0058A8'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '10',
    name: 'Manchester United Home Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Best price in Bangladesh for the iconic red home kit of Manchester United.',
    image: 'https://i.ibb.co.com/DDZChjXS/10.webp',
    colors: ['#DA291C', '#FFFFFF'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '11',
    name: 'AC Milan Home Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'AC Milan Jersey 2025. Classic Rossoneri stripes for the San Siro faithful.',
    image: 'https://i.ibb.co.com/YBfD3qpR/11.jpg',
    colors: ['#FB090B', '#000000'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '12',
    name: 'AC Milan Away Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'AC Milan White Jersey 2025. The lucky white kit for European nights.',
    image: 'https://i.ibb.co.com/QFN9T1Nx/12.jpg',
    colors: ['#FFFFFF', '#FB090B'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '13',
    name: 'Barcelona 125th Anniversary Jersey 2025',
    price: 1100,
    category: 'Football',
    description: 'Special edition kit celebrating 125 years of FC Barcelona excellence.',
    image: 'https://i.ibb.co.com/PGfMyfyq/13.webp',
    colors: ['#A50044', '#004D98'],
    sizes: ['S', 'M', 'L', 'XL'],
    isPopular: true
  },
  {
    id: '14',
    name: 'Real Madrid Third Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Real Madrid Blue Jersey 2025. Royal blue design for the kings of Europe.',
    image: 'https://i.ibb.co.com/KxNZK7rk/14.webp',
    colors: ['#00529F', '#FFFFFF'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '15',
    name: 'Barcelona Away Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Barcelona Mamba Jersey. Elite performance gear for every Culer.',
    image: 'https://i.ibb.co.com/Cs2FhmTG/15.webp',
    colors: ['#A50044', '#004D98'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '16',
    name: 'Inter Miami Third Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Inter Miami Jersey 2025. Best price in BD for the MLS heavyweights.',
    image: 'https://i.ibb.co.com/Swvx74nY/16.webp',
    colors: ['#F7B5CD', '#231F20'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '17',
    name: 'Chelsea Away Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Chelsea White Jersey 2025. The Pride of London on their travels.',
    image: 'https://i.ibb.co.com/Wv4jK7KQ/17.webp',
    colors: ['#FFFFFF', '#034694'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '18',
    name: 'Bayern Munich Home Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Bayern Munich Jersey 2025. Classic red and white for the Bavarian giants.',
    image: 'https://i.ibb.co.com/rR54nX51/18.jpg',
    colors: ['#DC052D', '#FFFFFF'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '19',
    name: 'Manchester United Away Kit 25/26',
    price: 1100,
    category: 'Football',
    description: 'Man Utd Jersey 2025. Best price for authentic premium quality.',
    image: 'https://i.ibb.co.com/HLRbZjFG/19.webp',
    colors: ['#FFFFFF', '#DA291C'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '20',
    name: 'Real Madrid Away Jersey 25/26',
    price: 1100,
    category: 'Football',
    description: 'Authentic Thai Premium Real Madrid Jersey 2025. Pure class for Madridistas.',
    image: 'https://i.ibb.co.com/0jLkL22c/20.jpg',
    colors: ['#FFCC00', '#FFFFFF'],
    sizes: ['S', 'M', 'L', 'XL'],
  }
];
